### ISSUE TITLE
Plugin zAuctionHouse-Discord v1.0.8 generated an exception while executing task 12356

### ISSUE THREAD

**Issue by deffuseyou** [Maxlego08/zAuctionHouse-Discord#12]
`java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.RegisteredServiceProvider.getProvider()" because "provider" is null
        at fr.maxlego08.discord.zcore.utils.ZUtils.getItemName(ZUtils.java:495) ~[zDiscord-1.0.8.jar:?]
        at fr.maxlego08.discord.listener.AuctionListener.replaceString(AuctionListener.java:216) ~[zDiscord-1.0.8.jar:?]
        at fr.maxlego08.discord.listener.AuctionListener.lambda$getBuilder$3(AuctionListener.java:180) ~[zDiscord-1.0.8.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.maxlego08.discord.listener.AuctionListener.getBuilder(AuctionListener.java:176) ~[zDiscord-1.0.8.jar:?]
        at fr.maxlego08.discord.listener.AuctionListener.lambda$onSell$0(AuctionListener.java:75) ~[zDiscord-1.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-199]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-199]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Maxlego08** [comment]
Error with spigot
