### ISSUE TITLE
Plugin.yml or plugin-paper.yml

### ISSUE THREAD

**Issue by RNAmaya** [Maxlego08/zAuctionHouse-Discord#19]
[23:09:19] [ServerMain/ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins/zAuctionHouseDiscord-1.1.1.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins/zAuctionHouseDiscord-1.1.1.jar' failed to update!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.Main.main(Main.java:128) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.Main.main(Main.java:336) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins/zAuctionHouseDiscord-1.1.1.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	... 21 more
Caused by: java.lang.IllegalArgumentException: plugins/zAuctionHouseDiscord-1.1.1.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:129) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	... 21 more

**Comment by j-speers** [comment]
Seeing the same issue making this plugin unusable , I'm running;
zAuctionHouse 3.2.2.4
zMenu 1.0.3.4
