### ISSUE TITLE
I encountered an error that restarts the server

### ISSUE THREAD

**Issue by thiagogebrimm** [Maxlego08/zAuctionHouse-Discord#4]
```
[21:52:40 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] There was an error in the WebSocket connection
java.lang.NoClassDefFoundError: net/dv8tion/jda/api/events/ShutdownEvent
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:460) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[zDiscord-1.0.5-jar-with-dependencies.jar-1.0.5.jar:?]
```

**Comment by Maxlego08** [comment]
Fix
